# Data for random names generation

# Templates

[templates]
name_gen_blabish = "<!name.blabish.first.pre><?name.blabish.first.mid><!name.blabish.first.post> von <!name.blabish.last.pre><!name.blabish.last.post>"
name_gen_english = "<!name.english.first.pre><?name.english.first.mid><!name.english.first.post> from <!name.english.last.pre><!name.english.last.post>"

[data]
pre = ["ah", "sah", "dah"]
post = ["bla", "fa"]
  [data.name]
    [data.name.blabish]
      [data.name.blabish.first]
      pre = ["A", "B", "D", "C"]
      mid = ["ra", "ba", "za"]
      post = ["hos", "bos", "dos"]
      [data.name.blabish.last]
      pre = ["Za", "Ba", "Da", "Ka", "Ze"]
      post = ["ba", "ha", "da", "re", "ka", "po"]
    [data.name.english]
      [data.name.english.first]
      pre = []
      mid = []
      post = []
      [data.name.english.last]
      pre = []
      post = []
